# Site settings
title: Juan Manuel Mougan's blog
email: juanmougan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog contains configuration and installation guides for diverses technologies.
baseurl: '' # the subpath of your site, e.g. /blog/
url: http://juanmougan.github.io/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jota_eme_eme
github_username: juanmougan

# Build settings
markdown: kramdown

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: juanmougan
